language: python
python: '2.7'
sudo: required
services:
- docker
before_install:
- pip install --upgrade setuptools
install:
- pip install ansible-container[docker]
script:
  - mkdir container
  - cd container
  - ansible-container install AAROC.CODE-RADE-build-containers
notifications:
  slack:
    secure: f/INZMWW9hwTgUik3d9p6DJxw5jnVOsSpNVWSTwYNfhuhq0T2tXHmI+SvFiN3bgutlLtWCR2vkCwt+nyDSXZ5z5hw9VApIi42YA6UUPqmZv7RYINEPOcEK8jEGaHTMn0CRRt1iuDw6Q87w8vtpfPskX8W0RrxraBZN2b3/FMBWrp71fkPmWmNZtbQNdGmw5XHmZ3IdDK4wV2iRlgsMYUS5ttYsKRNGg6zB5UWW+4BGAzYHny3MYr5P3DZ0d1v1RQoB/nRfjpk72Y3tdUAt47tTqRYdJ3VP/qAh+Nyq2/HpiW67BcFuQK6qJUfCIRw0vSLhf1W15ZU+8Mii1yr3TU7ZReeanluWnEBu8Y8eH7/pNXW3+FEO1GbXvpHOt17XDbMSrVcLblOhMD80NotqQjd5iOuHnVahv22mLTMUhqHySEVrm+YHn0Q4nBDk4y+2MsNWcCLgDftSfod5lLsLLDfqAA6EfJRP4+S3G+kuCEm+cudlpZ5600z08L7V28L4lAnohyVqQqu0WO5Es/H3LleQkquO2SGg2ZMvp0D2/+mDRAuk4z4wvXZLGALJu7NHpcrzOUFGPFoXK4msHqK4aWuWlrNovvKcbncWmAS+edOzo+Us/ujfWn7Ec/c5Majhda2pSqFdtvpGT1iMt9kPbq5eYEEANhw0lx3/E4ba/hEn0=
    on_success: change # default: always
    on_failure: always # default: always
