galaxy_info:
  author: Bruce Becker
  description: Build slave containers for CODE-RADE
  company: C.S.I.R. Meraka Institute

  license: license (GPLv2, CC-BY, etc)

  min_ansible_container_version: 0.9.3

  tags:
    - ci
    - jenkins
