version: "1"
services:
  build-slave:
    image: ubuntu:trusty
    user: jenkins
    ports:
      - "22:22"
    volumes:
      - /home/becker/SAGrid-2.0/gmp-deploy:/home/jenkins/workdir
    working_dir: /home/jenkins/workdir
    command: ['/bin/bash', '-xe', 'build.sh']


registries:
  docker:
    url: https://hub.docker.com
    namespace: /u/aaroc
  quay:
    url: https://quay.io
    namespace: aaroc
