version: "1"
services:
  build-slave:
    image: {{ base_image}}:{{ base_image_tag}}
    ports:
      - "{{ host_port }}:{{ container_port }}"
    command: ["/usr/sbin/sshd", "-D","-p {{ container_port}}"]
    volumes:
      - "/tmp:{{ src_dir }}"
registries:
  docker:
    url: https://hub.docker.com
    namespace: /u/aaroc
  quay:
    url: https://quay.io
    namespace: aaroc
