version: "1"
services:
  build-slave:
    image: "{{ base_image}}:{{ base_image_tag}}"
    ports:
      - "{{ host_port }}:{{ container_port }}"
    command: ["/usr/sbin/sshd", "-D","-p {{ container_port}}"]
    volumes_from:
      - CODE-RADE-src:rw
      - CODE-RADE-modules:rw
      - CODE-RADE-soft:rw
      - CODE-RADE-repo:rw
  CODE-RADE-src:
    image: alpine
    command: ["/bin/sh","-c","while true; do sleep 1000; done"]
    volumes:
      - "{{ src_dir }}"
  CODE-RADE-soft:
    image: alpine
    command: ["/bin/sh","-c","while true; do sleep 1000; done"]
    volumes:
      - "{{ soft_dir }}"
  CODE-RADE-repo:
    image: alpine
    command: ["/bin/sh","-c","while true; do sleep 1000; done"]
    volumes:
      - "{{ repo_dir }}"
  CODE-RADE-modules:
    image: alpine
    command: ["/bin/sh","-c","while true; do sleep 1000; done"]
    volumes:
      - "{{ modules_dir }}"


registries:
  docker:
    url: https://hub.docker.com
    namespace: /u/aaroc
  quay:
    url: https://quay.io
    namespace: aaroc
