version: "1"
services:
  build-slave:
    image: centos:7
    ports:
      - "22:22"
    command: ["/usr/sbin/sshd", "-D","-p 22"] 

registries:
  docker:
    url: https://hub.docker.com
    namespace: /u/aaroc
  quay:
    url: https://quay.io
    namespace: aaroc
